name = "ReSolver"
uuid = "9a172a43-bfaf-4cc4-8edb-b32fc4c49da3"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
FFTW = "1.10.0"
LinearAlgebra = "1.11.0"
Optim = "1.12.0"
Parameters = "0.12.3"
Printf = "1.11.0"
